version: "3.9"

services:
  traefik:
    image: traefik:v3.0 # latest stable
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  httpbin:
    image: kennethreitz/httpbin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.httpbin.rule=Host(`httpbin.localhost`)"
      - "traefik.http.routers.httpbin.entrypoints=web"

  # node-api:
  #   build: ./nod
  #   container_name: node-api
  #   networks:
  #     - traefik
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.nodeapi.rule=PathPrefix(`/api`)"
  #     - "traefik.http.routers.nodeapi.entrypoints=web"
  #     - "traefik.http.services.nodeapi.loadbalancer.server.port=3000"
  #   restart: unless-stopped

networks:
  traefik:
    external: true
